### ISSUE TITLE
训练模型不收敛

### ISSUE THREAD

**Issue by secortot** [dddzg/up-detr#1]
![图片](https://user-images.githubusercontent.com/38239721/111442016-dff68b00-8742-11eb-890b-a0b4d65159b7.png)
在自己的训练集上（已转换成coco格式，单类别检测）训练了170个epoch，loss基本不降，验证集AP也是0
 训练命令：python -m torch.distributed.launch --nproc_per_node=1 --use_env detr_main.py  --lr_drop 200 --epochs 300  --lr_backbone 5e-4 --pre_norm --coco_path /home/work/mnt/project/up-detr/data/coco --pretrain /home/work/mnt/project/up-detr/checkpoints/up-detr-pre-training-60ep-imagenet.pth

**Comment by dddzg** [comment]
我能问一下数据规模和整体检测的物体大小吗？  如果不是为了复现paper中 提到的结果的话  建议用 coco上微调后的权重，理论上效果会更好。 https://drive.google.com/file/d/1_YNtzKKaQbgFfd6m2ZUCO6LWpKqd7o7X/view?usp=sharing

**Comment by secortot** [comment]
> 我能问一下数据规模和整体检测的物体大小吗？ 如果不是为了复现paper中 提到的结果的话 建议用 coco上微调后的权重，理论上效果会更好。 https://drive.google.com/file/d/1_YNtzKKaQbgFfd6m2ZUCO6LWpKqd7o7X/view?usp=sharing

感谢回复
数据规模大概12K街景图片，检测图片中的招牌，尺度差异比较大，我用的ImageNet的预训练模型训练的，尝试一下coco的预训练模型

**Comment by dddzg** [comment]
我再简单补充一下一些细节：
1. 如果图片大小没有coco这么大（短边600-800像素）的话，你可以考虑 https://github.com/dddzg/up-detr/blob/master/datasets/coco.py#L121 修改一下这边的大小，会显著加快收敛速度。
2. 可能你还得注意一下 你图片中  检测的目标的数量  如果 目标的数量很少的话 可以把 --eos_coef 调小一点  默认是0.1  大概是一张图片平均有10个object左右
3. 还有看起来 你这边只有一张卡，可能收敛会更困难一些（不是很确定）。 建议到200ep 再观察一下

祝你好运~

**Comment by secortot** [comment]
> 我再简单补充一下一些细节：
> 
>     1. 如果图片大小没有coco这么大（短边600-800像素）的话，你可以考虑 https://github.com/dddzg/up-detr/blob/master/datasets/coco.py#L121 修改一下这边的大小，会显著加快收敛速度。
> 
>     2. 可能你还得注意一下 你图片中  检测的目标的数量  如果 目标的数量很少的话 可以把 --eos_coef 调小一点  默认是0.1  大概是一张图片平均有10个object左右
> 
>     3. 还有看起来 你这边只有一张卡，可能收敛会更困难一些（不是很确定）。 建议到200ep 再观察一下
> 
> 
> 祝你好运~

感谢大佬，目前是打算在本地离线服务器测试，后续会放到集群上训练
另外，使用coco的预训练模型之后，确实loss开始平稳下降了
数据集图片分辨率是1920*1080的，我预处理的时候同一resize到1333*800了
eos这个参数倒是还没注意到，后续我调整一下看看效果
再次感谢！

**Comment by dddzg** [comment]
有问题再联系啦

**Comment by xiaoerlaigeid** [comment]
你好 想问下加载该预训练模型 COCO finetune_300.pth 时候出现 msg _IncompatibleKeys(missing_keys=['class_embed.weight', 'class_embed.bias'], unexpected_keys=['transformer.encoder.norm.weight', 'transformer.encoder.norm.bias']) 这是正常的吗？ 我也训练自己数据效果很差在验证集
