### ISSUE TITLE
Evaluate the fine-tuned model

### ISSUE THREAD

**Issue by wilderrodrigues** [dddzg/up-detr#11]
Hi again, @dddzg

I'm trying to evaluate the model I fine-tuned on a separate dataset, that doesn't contain annotations (as it suppose to be). According to the docs in the readme, you did the evaluation step using the COCO val5k - which contains only images.

When I try the same, I get an error due to the non-existence of the `instances_val2017.json`. For evaluation purposes, those should not be required.

_The path below has been edited for simplicity._
```
FileNotFoundError: [Errno 2] No such file or directory: '.../annotations/instances_val2017.json'
```

Thanks in advance.

**Comment by wilderrodrigues** [comment]
Sorry, I think I made a mistake because I can't find the val5k annotations on the COCO dataset website (https://cocodataset.org/#download). So, I assumed you ran the evaluation on images only.

**Comment by dddzg** [comment]
Yes, we need ground truth file for evaluating instead of images only.
