### ISSUE TITLE
Some questions about your code

### ISSUE THREAD

**Issue by Huzhen757** [dddzg/up-detr#14]
Hi, I'm very interested in your work about the newly object query in decoder of Transformer through the cropped patches form original images,  but when I debug the code, I find it's report the error, like this:
![6aad2771224a98ff46a22c2d74df0db](https://user-images.githubusercontent.com/65730183/136699959-fe9d721f-1595-4b3d-ae3d-bfcc40ca796e.png)

In the code, I didn't find anything about the generation of patches and the call of forward propagation process，due to the forward function of UP-DETR need the patches inputs. 
Besides,  I use COCO2017-train dataset for pre-training dataset,  I find the process of finetune is absolutely same as  DETR，so I want to study the pre-training process，in other words，I want to look the UP-DETR how works，especially in the decoder part.

I sincerely hope you can give some solutions, Thanks !

**Comment by dddzg** [comment]
Thanks for your attention. The paches input is generated during the pre-training in https://github.com/dddzg/up-detr/blob/be066dfca5e8f1f35a4331490e8239b579bbf497/datasets/selfdet.py#L18

For UP-DETR, the model is pre-trained on ImageNet (by running `main.py`) and fine-tuned on COCO (by running `detr_main.py`).
For pre-training and fine-tuning code, we share the `engine.py` file. 
Please check https://github.com/dddzg/up-detr#unsupervised-pre-training for more details about how to pre-train UP-DETR on ImageNet.

You can try to read the code in `datasets/selfdet.py` and `models/updetr.py` for more details about the pre-training procedure.

**Comment by dddzg** [comment]
Feel free to re-open the issue if you have any other questions.

**Comment by dddzg** [comment]
No. We expect the directory structure of the pre-training to be the following:
```
path/to/imagenet/
  n06785654/  # caterogey directory
    n06785654_16140.JPEG # images
  n04584207/  # caterogey directory
    n04584207_14322.JPEG # images
```

You can adjust the code in https://github.com/dddzg/up-detr/blob/be066dfca5e8f1f35a4331490e8239b579bbf497/datasets/selfdet.py#L46
to support coco2017 as the pre-training dataset.
