### ISSUE TITLE
How extract precision, recall and f1-score metrics

### ISSUE THREAD

**Issue by jackonealll** [dddzg/up-detr#17]
Hello thank you for sharing the code.

I would like to know how to extract **precision**, **recall** and **f1-score** metrics. I already have the AP and AR metrics.

I am trying to use the following code but it gives me a numpy matrix:

```
precision = coco_eval.eval['precision']
recall = coco_eval.eval['recall']
```
Can you help me?

**Comment by dddzg** [comment]
I am sorry that this issue is not related to our work. I guess you can find more details in [pycocotools](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py)
