### ISSUE TITLE
Code for VOC

### ISSUE THREAD

**Issue by zhihou7** [dddzg/up-detr#18]
Thanks for your interesting work, 

Would you mind releasing the training code for PASCAL VOC?

Regards,

**Comment by dddzg** [comment]
It is easy to run our code with VOC: 
1. Converting the VOC dataset from xml to coco style json.
2. changing the paths file.
https://github.com/dddzg/up-detr/blob/be066dfca5e8f1f35a4331490e8239b579bbf497/datasets/coco.py#L158

**Comment by Kyfafyd** [comment]
Could you please provide the converted VOC annotations in coco style json files?
I have tried to do this, but meet some errors.
