### ISSUE TITLE
detectiong objects

### ISSUE THREAD

**Issue by sunwei317** [dddzg/up-detr#19]
In DETR, only the image is needed for object detection. But in UP-DETR, it needs an extra list of patchs to detect objects. Why? the list of patchs could be fixed for all images if only detectiong objects? Thank you for the interesting work!

**Comment by dddzg** [comment]
Patches are randomly cropped from the original image during the pre-training.
Check the code for more details.
https://github.com/dddzg/up-detr/blob/be066dfca5e8f1f35a4331490e8239b579bbf497/datasets/selfdet.py#L69
