### ISSUE TITLE
Class Loss

### ISSUE THREAD

**Issue by DoublePan-Oh** [dddzg/up-detr#20]
![image](https://user-images.githubusercontent.com/30366011/160341779-044bf194-65bd-4b8c-bf80-7ae052a2866c.png)
I didn't find this parameter in your code. Can you tell me which one?

As I know, the CNN backbone does not participate in training, but is only used to extract image features. Can CNN and transformer be separated. For example, first use Resnet to extract image features, and then randomly crop patch at the feature level. I mean starting from features.
I plan to use this idea to do video tasks, but I can't directly manipulate the video itself, I can only start from the video features. I don't know if this is possible.

**Comment by dddzg** [comment]
1. The parameter is `eos_coef`. As the M=10,N=100, so eos_coef is 0.1.
2. Yes, I think the idea could work with the pre-extracted features during the pre-training. And then, fine-turning the whole weights.

**Comment by dddzg** [comment]
Re-open the issue if you have any questions.
