### ISSUE TITLE
SWAV

### ISSUE THREAD

**Issue by DoublePan-Oh** [dddzg/up-detr#21]
Is updetr very dependent on pre-trained CNN? Why choose SWAV? Can other Unsupervised Learning replace SWAV?

**Comment by dddzg** [comment]
> Is updetr very dependent on pre-trained CNN? 

Yes. But I think other unsuperivsed pre-trained CNNs could also work.

 > Why choose SWAV?

Because before our paper, SwAV mentioned it reduce the trianing time of DETR by unsupervised CNN. So, we have to refer it.

> Can other Unsupervised Learning replace SWAV?

I think other unsuperivsed CNNs could replace SwAV, but there is no more experiments.
