### ISSUE TITLE
Random Crop

### ISSUE THREAD

**Issue by DoublePan-Oh** [dddzg/up-detr#22]
Can we randomly crop from other image and paste it on the training picture, and also use the randomly cropped as a pseudo-label, that is, find the cropped block in the original image？

**Comment by DoublePan-Oh** [comment]
I don't know if this  guess is correct？

**Comment by DoublePan-Oh** [comment]
I don't know if this guess is correct or not？

**Comment by dddzg** [comment]
I am not sure. In my perspective, I think it could work.
