### ISSUE TITLE
How to get the inference time (speed) ?

### ISSUE THREAD

**Issue by ilem777** [dddzg/up-detr#3]
❓ How to get the inference time or speed using UP-DETR?

I want to make some comparisons between some models, how can I export (print) the inference time when testing or evaling UP-DETR?

**Comment by dddzg** [comment]
Hi @ilem777 , it depends on what you are applying UP-DETR for.
If you are applying UP-DETR for object detection, it has the exact same inference time as DETR (28fps on V100 with standard COCO val2017 images). Checking more details about the inference time of DETR in https://github.com/facebookresearch/detr/issues/110.

**Comment by ilem777** [comment]
@dddzg Thank you for your prompt response. Yes, I am using custom object detection dataset in COCO format, I have finished training the model and now I want to train the model, I will try your suggestion.

**Comment by dddzg** [comment]
Good luck!

**Comment by ilem777** [comment]
@dddzg Hello, how can I run the "computer_flops.py" file?
I changed PATH_TO_COCO in line 52 to my custom dataset path.
Then I run it, why does it automatically download a model to test it?
I think I should change lines 59~63
```
device = torch.device('cuda')
results = {}
for model_name in ['detr_resnet50']:
    model = torch.hub.load('facebookresearch/detr', model_name, pretrained=True)
    model.to(device)
````
How can I modify these lines to read my trained model? The path of my trained model is in "outputs/checkpint.pth". Thank you, this is really bothering me.

Also I would like to ask how to run the "util/plot_utils.py" file? I don't see any tutorials on the discussion forum, how can I run it? Also, the "log.txt" file is in the "outputs" folder. Thank you very much.
