### ISSUE TITLE
What file does "files" in def plot_precision_recall(files, naming_scheme='iter') refer to and which file do I need?

### ISSUE THREAD

**Issue by ilem777** [dddzg/up-detr#4]
Hello, I see that `./util/plot_utils.py` file can plot PR curves, but it requires a "files", what does this "files" refer to?
`def plot_precision_recall(files, naming_scheme='iter'):`
Is it `./outputs/log.txt` file?
Or is it any of the `./outputs/checkpoint.pth`?
Or should I need the `./outputs` folder?

Thank you.

**Comment by dddzg** [comment]
Neither of them. The code is not used in our repo.

**Comment by ilem777** [comment]
@dddzg I'm really sorry, I've re-edited the problem description, can you please take a look at it? This line of code is in your repository, but I don't know how to use it...

**Comment by dddzg** [comment]
It is not used by us. According to the code implementation, the file will be load by totch.load. The implementation is not complex, so you can check and modify the code as your requirement.

**Comment by ilem777** [comment]
All right, thank you. I will try it.
